server:
  port: 8888

proxy:
  servers: http://localhost:8801,http://localhost:8802,http://localhost:8803
  weight: 3,2,1

netty:
  group:
    boss: 1
    worker: 16

router:
  choose:
    type: weight